[package]
name = "adventofcode24"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
indicatif = "0.17.9"
itertools = "0.13.0"
log = { version = "0.4.22" }
regex = "1.11.1"
stderrlog = "0.6.0"
